#!/usr/bin/env bash
# Process and PID file
# Creates a file containig its PID
# Displays To infinty and beyond indefinitely
# Displays I hate the kill command when SIGTERM signal is received
# Displays Y u no love me?! when receiving SIGINT signal
# deletes the created file and terminates itself when SIGQUIT or SIGTERM signal is received.

function love() {
    rm /var/run/myscript.pid
    exit
}

trap "echo I hate the kill command;love" SIGTERM
trap "echo Y U no love me?!;love" SIGINT

echo '$$' >> /var/run/myscript.pid
while true
do
    echo To infinity and beyond;
done
