#!/usr/bin/env bash
# displays To infinity and beyond and I am invincible when receiving a SIGTERM signal

while true
do
	echo "To infinty and beyond"
	sleep 2
	trap 'echo "I am invincible"' SIGTERM
done
