#!/usr/bin/env bash
# Displays numbers from 1 to 100
# Displays FizzBuzz when number is a multiple of 3 and 5
# Displays Fizz when number is a multiple of 3
# Displays Buzz when number is a multiple of 5
# Otherwise display the number

i=1
while [ $i -le 100 ]
do
	if (((i % 3 == 0) && ( i % 5 == 0)))
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0))
	then
		echo "Fizz"
	elif (( i % 5 == 0))
	then
		echo "Buzz"
	else	
		echo "$i"
	fi
	(( i++ ))
done
