#!/usr/bin/env bash
# Loops from 1 to 10.Displays bad luck on the 4th loop, good luck on the 8th loop and Best School for the rest.

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
